version: '3.8'
services:
  # ... (other services)
  kms1:  
    build: .
    environment:
      PRIVATE_KEY_WIF: "cQGcfGErsc2QwuKvh2djWNjav2SCJ9ZWGVPcedn2MuNC5wPUpMt6"
    ports:
      - "8081:8080"  # Example: map container port 8080 to host port 8081
  # (Repeat for other KMS instances with different private key shares and ports)